### ISSUE TITLE
甲骨文ARM的debian10，DD后密码不对啊

### ISSUE THREAD

**Issue by xiaoyaoz1** [honorcnboy/BlogDatas#1]
10086.fit，是我操作问题？

**Comment by github-office** [comment]
dabian密码正确，但是ubuntu密码不正确

**Comment by cookrs** [comment]
> dabian密码正确，但是ubuntu密码不正确

确实ubuntu密码不正确

**Comment by honorcnboy** [comment]
请使用《[甲骨文云服务器忘记密码/丢失密钥的解决办法-新篇](https://cnboy.org/2793)》更新密码或添加秘钥。近期将更新新包，采用密码 & 密钥双登录。
